import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.scss";
import TopBar from "../components/TopBar/TopBar";
import SideBar from "../components/SideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.layout}`}>
        <TopBar />
        <div className={` ${styles.layout_index_container}`}>
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
